### ISSUE TITLE
how it detect the heading ? 

### ISSUE THREAD

**Issue by gemad** [gestom/CosPhi#5]
the circle is symmetric so how it detect the heading ? 
+
when i click a it used to set the outer pattern as the boarders but now it only give strange numbers

**Comment by gestom** [comment]
1) Make sure that you use the correct version for the localisation system. lrse/whycon is not the same as CosPhi/localization. The list of the individual versions is mentioned here: https://github.com/gestom/whycon.

2) For heading, you need to generate the patterns (in CosPhi/localisation) as indicated in the second step of "Advanced setup for more robots in a rectangular field" https://github.com/gestom/CosPhi/tree/master/Localization". These patterns are not symmetric, but slightly elliptic, which allows for heading estimation. The inner ellipses differ slightly, which encodes the ID.

3) Let me know about auto-calibration after you try the CosPhi/localization version.

**Comment by gemad** [comment]
thanks alot , that was very helpful ! , i will try and let you now , the CosPhi doesn’t support ROS yet am i right ?

**Comment by gestom** [comment]
Nono, it does not support ROS, but IMHO making a ROS wrapper should not be difficult. You could just make a small node that would listen to the TCP output of CosPhi and republish it as a ROS message.

**Comment by gemad** [comment]
i will and i will contribute with it here (Y)
